name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src-llama

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Package Manager
        id: detect-package-manager
        run: |
          if [ -f "yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: |
            ./src-llama/package-lock.json
            ./src-llama/yarn.lock

      - name: Setup GitHub Pages Config
        id: pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Install Dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build Next.js App
        env:
          NEXT_PUBLIC_BASE_PATH: ${{ steps.pages.outputs.base_path }}
        run: ${{ steps.detect-package-manager.outputs.manager }} run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src-llama/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4